export const RECIPE_CATEGORIES = [
  { value: 'breakfast', label: 'Desayuno' },
  { value: 'lunch', label: 'Almuerzo' },
  { value: 'dinner', label: 'Cena' },
  { value: 'appetizer', label: 'Entrada / Aperitivo' },
  { value: 'main-course', label: 'Plato fuerte' },
  { value: 'side-dish', label: 'Acompañamiento' },
  { value: 'pasta', label: 'Pasta' },
  { value: 'rice', label: 'Arroz' },
  { value: 'salad', label: 'Ensalada' },
  { value: 'soup', label: 'Sopa / Crema' },
  { value: 'bread', label: 'Pan / Panadería' },
  { value: 'pizza', label: 'Pizza' },
  { value: 'bbq', label: 'Parrilla / BBQ' },
  { value: 'seafood', label: 'Mariscos / Pescado' },
  { value: 'vegetarian', label: 'Vegetariano' },
  { value: 'dessert', label: 'Postre' },
  { value: 'snack', label: 'Snack' },
  { value: 'drink', label: 'Bebida' },
  { value: 'sauce', label: 'Salsa' },
  { value: 'other', label: 'Otra' },
];
